name: Haskell CI

on:
  workflow_dispatch:
  push:

jobs:
  build:
    name: Build with ${{ matrix.ghc }} / ${{ matrix.cabal }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ['8.10', '9.0', '9.2', '9.4', '9.6']
        cabal: ['3.10']
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Setup Haskell
      uses: haskell/actions/setup@v2
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}
    - uses: actions/cache@v3
      name: Cache dist-newstyle
      with:
        path: |
          ~/.cabal/packages
          ~/.cabal/store
          dist-newstyle
        key: ${{ matrix.os }}-${{ matrix.ghc }}-0-cabal
    - name: Update package database
      run: cabal update
    - name: Install build dependencies
      run: cabal build --only-dependencies
    - name: Build
      run: cabal build --enable-tests
    - name: Install test dependencies
      run: cabal build --only-dependencies --enable-tests
    - name: Run tests
      run: cabal test --enable-tests
